apiVersion: v1
kind: Service
metadata:
  name: raas-service
  namespace: dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # or "clb" for Classic LB (optional)
spec:
  selector:
    app: raas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
