apiVersion: v1
kind: Service
metadata:
  name: raas-service
  namespace: dev   # Change to prod if needed
spec:
  type: LoadBalancer
  selector:
    app: raas
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
