apiVersion: v1
kind: Service
metadata:
  name: raas-service
  namespace: dev    # (make sure it matches your deployment namespace)
  labels:
    app: raas
spec:
  type: LoadBalancer    # <-- Exposes service externally (AWS ELB created automatically)
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: raas
